###############################################
# DriveBackup   -   by Max Maeder (MaxTheGinus)
###############################################

# IMPORTANT: Make sure any file paths you specify don't end with a file seperator (usually "/")

# How often to do backups (in minutes), set to -1 to disable automatic backups
delay: 60
# The priority of the backup thread, relative to the default
# For example, -1 would make the prioriy one less than the default
backup-thread-priority: 0
# How many backups to keep remotely before deleting the oldest one, set to -1 to disable automatic deletes
keep-count: 20
# How many backups to keep locally before deleting the oldest one, set to -1 to disable automatic deletes
local-keep-count: 0
# Should automatic backups be disabled if there hasn't been any new player activity since the last backup
backups-require-players: true

# Should backups run at specific days/times every week, instead of every so often?
scheduled-backups: false
# The timezone the times in the schedule are in
# Example timezones:
#   Chicago, USA: "-05:00"
#   Paris, France: "+02:00"
# Find your timezone: http://www.timeanddate.com/time/map/
schedule-timezone: "-00:00"
# Expandable list of dates/times to back up
backup-schedule-list:
# An entry is comprised of two things:
#   - The day(s) to run the backup on
#   - The time to run the backup at
#
# The day(s) to run the backup on should be a list comprised of any of the following:
#   - Days of the week: "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", or "saturday"
#   - Groups of days: "weekdays" or "weekends"
#   - All days: "everyday"
#
# The time to run the backup at should be in 24-hour format
# If the time is before 10 o'clock, there must be a zero in front of the hour
# For example: 03:00 (3 AM) or 13:00 (1 PM)
- days: 
  - "sunday"
  - "wednesday"
  time: "05:00"
- days: 
  - "monday"
  - "thursday"
  time: "23:30"

# Expandable list of things to back up
backup-list:
# An entry is comprised of four things:
#   - the folder path
#   - the file name format
#   - whether this plugin should create the backup, or just upload it
#   - files to not include in the backup (optional)
#
# The folder path should be the path to the folder you want to backup, 
#   relative to the folder your server jar is in
# For more information about relative paths, see
#   http://www.linux.com/training-tutorials/absolute-path-vs-relative-path-linuxunix/
# To avoid overwriting data, ".." only affects the current working directory locally
#
# The file name format is the backup's naming scheme, this should contain a timestamp
# For more information about timedate formatting, see
#   http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html
# Correct formatting is important, as this is how the plugin knows
#   which backup is the most recent!
#
# You can also use the blacklist to not include specified files/folders
# An entry should be the path to the file/folder relative to the folder you want to backup, for example:
#   blacklist:
#     - "dontbackup"
#     - "thesefolders"
#     - "orthisfile.txt"
- path: "world"
  format: "'Backup-world-'yyyy-M-d--HH-mm'.zip'"
  create: true
- path: "plugins"
  format: "'Backup-plugins-'yyyy-M-d--HH-mm'.zip'"
  create: true

# Path to the folder to save backups in locally
dir: "backups"

# Path to the folder to save backups in on the remote server
destination: "backups"

# Backup methods
googledrive:
  enabled: false
onedrive:
  enabled: false
ftp:
  enabled: false
  # Server to connect to
  hostname: "ftp.example.com"
  # Port to connect to (usually 21 for FTP and 22 for SFTP)
  port: 21
  # Set to true to use SFTP instead of FTP
  sftp: false
  # Set to true to use FTPS instead of FTP
  ftps: false
  # Username
  username: "Username"
  # Password  (leave blank if no password)
  password: 
  # Path to the SFTP public key, relative to the "DriveBackupV2 folder" (leave blank if not using public key authentication)
  sftp-public-key: 
  # SFTP passphrase (leave blank if not using public key authentication or no password)
  sftp-passphrase: 
  # The directory to work in (leave blank for default)
  working-dir:

# Messages
messages:
  # What to say to a player who attempts to preform an action they don't have permission to do
  no-perm: "You don't have permission to do this!"
  # What to say to all players when backup starts
  backup-start: "Creating backups, server may lag for a little while..."
  # What to say to all players when backup is complete
  backup-complete: "Backup complete,"
  # What to say to all players when a interval-based backup is complete
  # This message is sent along with "backup-complete"
  #   %TIME is the amount of time until the next backup, in minutes
  next-backup: "the next backup is in %TIME minutes"
  # What to say to all players when a schedule-based backup is complete
  # This message is sent along with "backup-complete"
  #   %DATE is the date/time of the next backup
  next-schedule-backup: "the next backup is at %DATE"
  # The format of the time/date represented by %DATE in the "next-schedule-backup" message
  # For more information about timedate formatting, see
  #   http://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
  next-schedule-backup-format: "hh:mm a EEE, MMM dd"

# Advanced
advanced:
  # Should metrics be enabled?
  metrics: true
  # Should the plugin look for updates?
  update-check: true
  # Suppress most stacktraces?
  suppress-errors: false
  # FTP file seperator
  ftp-file-seperator: "/"