###############################################
# DriveBackup   -   by Max Maeder (MaxTheGinus)
###############################################

# IMPORTANT: Make sure any file paths you specify don't end with a file seperator (usually "/")

# How often to do backups (in minutes), set to -1 to disable automatic backups
delay: 60
# The priority of the backup thread, relative to the default
# For example, -1 would make the prioriy one less than the default
backup-thread-priority: 0
# How many backups to keep before deleting the oldest one, set to -1 to disable automatic deletes
keep-count: 20

# Expandable list of things to back up
backup-list:
# An entry is comprised of a a list of four things:
#   - the folder path
#   - the file name format
#   - whether this plugin should create the backup, or just upload it
#   - files to not include in the backup (optional)
#
# The folder path should be the path to the folder you want to backup, 
#   relative to the folder your server jar is in
# For more information about relative paths, see
#   http://www.linux.com/training-tutorials/absolute-path-vs-relative-path-linuxunix/
# To avoid overwriting data, ".." only affects the current working directory locally
#
# The file name format is the backup's naming scheme, this should contain a timestamp
# For more information about timedate formatting, see
#   http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html
# Correct formatting is important, as this is how the plugin knows
#   which backup is the most recent!
#
# You can also use the blacklist to not include specified files/folders
# An entry should be the path to the file/folder relative to the folder you want to backup, for example:
#   blacklist:
#     - "dontbackup"
#     - "thesefolders"
#     - "orthisfile.txt"
#
# For example, if you wanted to back up crash reports, you would do:
#  - path: "crash-reports"
#    format: "'crash-'yyyy-MM-dd_HH.mm.ss'-server.zip'"
#    create: true
# The crash-reports: part refers to the folder, and the "'crash-'yyyy-MM-dd_HH.mm.ss'-server.txt'" refers to
#   what format the file name is. Since create is set to true, the plugin will take the crash-reports folder,
#   zip it into a file according to the format, and upload it
  - path: "world"
    format: "'Backup-world-'yyyy-M-d--HH-mm'.zip'"
    create: true
  - path: "plugins"
    format: "'Backup-plugins-'yyyy-M-d--HH-mm'.zip'"
    create: true

# Path to the folder to save backups in locally
dir: "backups"

# Path to the folder to save backups in on the remote server
destination: "backups"

# Keep backups locally in backup directory after remote upload?
keep-local-backup-after-upload: false

# Backup methods
googledrive:
  enabled: false
onedrive:
  enabled: false
ftp:
  enabled: false
  # Server to connect to
  hostname: "ftp.example.com"
  # Port to connect to (usually 21 for FTP and 22 for SFTP)
  port: 21
  # Set to true to use SFTP instead of FTP
  sftp: false
  # Set to true to use FTPS instead of FTP
  ftps: false
  # Username
  username: "Username"
  # Password  (leave blank if no password)
  password: 
  # Path to the SFTP public key, relative to the "DriveBackupV2 folder" (leave blank if not using public key authentication)
  sftp-public-key: 
  # SFTP passphrase (leave blank if not using public key authentication or no password)
  sftp-passphrase: 
  # The directory to work in (leave blank for default)
  working-dir:

# Messages
messages:
  # What to say to a player who attempts to preform an action they don't have permission to do
  no-perm: "You don't have permission to do this!"
  # What to say to all players when backup starts
  backup-start: "Creating backups, server may lag for a little while..."
  # What to say to all players when backup is complete
  backup-complete: "Backup complete"
  # What to say to all players when backup is complete and there is another scheduled backup
  # This message is sent along with "backup-complete"
  #   %TIME is the amount of time until the next backup, in minutes
  next-backup: "The next backup is in %TIME minutes"

# Advanced
advanced:
  # Should metrics be enabled?
  metrics: true
  # Should the plugin look for updates?
  update-check: true
  # Suppress most stacktraces?
  suppress-errors: false
  # FTP file seperator
  ftp-file-seperator: "/"