###############################################
# DriveBackup   -   by Max Maeder (MaxTheGinus)
###############################################

# DOCUMENTATION HAS MOVED
# Now available online at: https://github.com/MaxMaeder/DriveBackupV2/wiki

delay: 60
backup-thread-priority: 0
keep-count: 20
local-keep-count: 0
backups-require-players: true

scheduled-backups: false
schedule-timezone: "-00:00"
backup-schedule-list:

backup-list:
- path: "world"
  format: "'Backup-world-'yyyy-M-d--HH-mm'.zip'"
  create: true
- path: "plugins"
  format: "'Backup-plugins-'yyyy-M-d--HH-mm'.zip'"
  create: true

external-backup-list:

dir: "backups"

destination: "backups"

googledrive:
  enabled: false
  team-drive-name: 
onedrive:
  enabled: false
ftp:
  enabled: false
  hostname: "ftp.example.com"
  port: 21
  sftp: false
  ftps: false
  username: "Username"
  password: 
  sftp-public-key: 
  sftp-passphrase: 
  working-dir:

messages:
  send-in-chat: true
  no-perm: "You don't have permission to do this!"
  backup-start: "Creating backups, the server may lag for a little while..."
  backup-complete: "Backup complete,"
  next-backup: "the next backup is in %TIME minutes"
  next-schedule-backup: "the next backup is at %DATE"
  next-schedule-backup-format: "h:mm a EEE, MMM d"

advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  prefix-chat-messages: true
  date-language: "en"
  ftp-file-seperator: "/"