name: DriveBackupV2
version: 1.1.1
description: Uploads backups to Google Drive/OneDrive or by (S)FTP
main: ratismal.drivebackup.DriveBackup
author: MaxTheGinus
commands:
  driveBackup:
    description: See all DriveBackup commands
    usage: /drivebackup